Taller práctico - SQL
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/R-for-data-science/blob/master/01-uso-interactivo.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/R-for-data-science/blob/master/01-uso-interactivo.ipynb) para ver la última versión online en `nbviewer`. 

---

## Descripción del problema

Usted ha sido elegido como gerente de talento humano de una compañía manufacturera que se dedica a la producción y comercialización de un producto orgánico a base de caña de azucar, en Colombia. Su primera tarea consiste en incluir la información sobre los empleados, que reposan hoy en día en archivos de Excel, en una base de datos estructurada y a continuación evaluar la equidad de salarios entre los cargos.

Los archivos contienen de la siguiente información:

> **salarios.csv**
    
         > empleado_id = Identificación del empleado
         > salario = Salario mensual en USD
         > desde = Fecha de inicio del contrato actual 
         > hasta = Fecha de finalización del contrato actual

> **empleados.csv**
    
         > empleado_id 
         > nombre 
         > f_nacimiento = Fecha de nacimiento
         > departamento_id = Identificación del departamento al que pertenece
         > SesionLog = identificación de la persona que recolectó la información.
         
> **contacto.csv**
    
         > empleado_id 
         > celular = Teléfono celular del empleado
         > dirección 
         > email
         > teléfono
         
> **departamento.csv**
    
         > empleado_id 
         > departamento_id
         > departamento 
         > cargo
         
         
A partir del planteamiento anterior, responda ante los siguientes requerimientos de información:

In [1]:
from traitlets.config import Bool, Unicode

In [2]:
%load_ext sql

In [3]:
%sql mysql+pymysql://root:sistemas@localhost

C:\Users\Unalmed\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xEDfico,...' for column 'VARIABLE_VALUE' at row 518")
  result = self._query(query)
C:\Users\Unalmed\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (3719, "'utf8' is currently an alias for the character set UTF8MB3, which will be replaced by UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.")
  result = self._query(query)


'Connected: root@None'

### Requerimiento 1. 
Cree una base de datos llamada `talento humano`.


In [5]:
%sql CREATE DATABASE talento_humano;

 * mysql+pymysql://root:***@localhost
1 rows affected.


[]

In [6]:
%sql use talento_humano;

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

### Requerimiento 2. 
De acuerdo con los archivos existentes, cree tablas en la base de datos que permitan almacenar toda la información.

In [7]:
%%sql 
CREATE TABLE IF NOT EXISTS 
contacto(empleado_ID CHAR(15),celular VARCHAR(15),direccion VARCHAR(50),email CHAR(50),telefono VARCHAR(25));

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [11]:
%sql DESCRIBE contacto;

 * mysql+pymysql://root:***@localhost
5 rows affected.


[('empleado_ID', 'char(15)', 'YES', '', None, ''),
 ('celular', 'varchar(15)', 'YES', '', None, ''),
 ('direccion', 'varchar(50)', 'YES', '', None, ''),
 ('email', 'char(50)', 'YES', '', None, ''),
 ('telefono', 'varchar(25)', 'YES', '', None, '')]

In [8]:
%%sql
CREATE TABLE IF NOT EXISTS 
departamento(empleado_ID CHAR(15),departamento_ID CHAR(5),departamento VARCHAR(20),cargo VARCHAR(20)); 

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [16]:
%sql DESCRIBE departamento;

 * mysql+pymysql://root:***@localhost
4 rows affected.


[('empleado_ID', 'char(15)', 'YES', '', None, ''),
 ('departamento_ID', 'char(5)', 'YES', '', None, ''),
 ('departamento', 'varchar(20)', 'YES', '', None, ''),
 ('cargo', 'varchar(20)', 'YES', '', None, '')]

In [9]:
%%sql
CREATE TABLE IF NOT EXISTS 
empleados(empleado_ID CHAR(15),nombre VARCHAR(25),f_nacimiento DATE,departamento_ID CHAR(5), SesionLog CHAR(10));

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [18]:
%sql DESCRIBE empleados;

 * mysql+pymysql://root:***@localhost
5 rows affected.


[('empleado_ID', 'char(15)', 'YES', '', None, ''),
 ('nombre', 'varchar(25)', 'YES', '', None, ''),
 ('f_nacimiento', 'date', 'YES', '', None, ''),
 ('departamento_ID', 'char(5)', 'YES', '', None, ''),
 ('SesionLog', 'char(10)', 'YES', '', None, '')]

In [10]:
%%sql
CREATE TABLE IF NOT EXISTS 
salarios(empleado_ID CHAR(15),salario INT,desde DATE,hasta DATE);

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [21]:
%sql DESCRIBE salarios;

 * mysql+pymysql://root:***@localhost
4 rows affected.


[('empleado_ID', 'char(15)', 'YES', '', None, ''),
 ('salario', 'int(11)', 'YES', '', None, ''),
 ('desde', 'date', 'YES', '', None, ''),
 ('hasta', 'date', 'YES', '', None, '')]

### Requerimiento 3. 
Establezca el ID de empleado como el registro de identificación en la base de datos, es decir, como la clave primaria de las tablas creadas. 

In [11]:
%%sql
ALTER TABLE empleados MODIFY COLUMN empleado_ID INT PRIMARY KEY;

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [41]:
%sql DESCRIBE empleados;

 * mysql+pymysql://root:***@localhost
4 rows affected.


[('empleado_ID', 'int(11)', 'NO', 'PRI', None, ''),
 ('nombre', 'varchar(25)', 'YES', '', None, ''),
 ('f_nacimiento', 'date', 'YES', '', None, ''),
 ('departamento_ID', 'char(5)', 'YES', '', None, '')]

In [12]:
%%sql
ALTER TABLE salarios MODIFY COLUMN empleado_ID INT PRIMARY KEY;

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [13]:
%%sql
ALTER TABLE departamento MODIFY COLUMN empleado_ID INT PRIMARY KEY;

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

In [14]:
%%sql
ALTER TABLE contacto MODIFY COLUMN empleado_ID INT PRIMARY KEY;

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

### Requerimiento 4. 
Cargue la información de los archivos a la base de datos.

In [16]:
%%sql
LOAD DATA INFILE 'contacto.csv' INTO TABLE contacto FIELDS TERMINATED BY ';' IGNORE 1 LINES (empleado_ID,celular,direccion,email,telefono);

 * mysql+pymysql://root:***@localhost
20 rows affected.


[]

In [17]:
%%sql
LOAD DATA INFILE 'departamento.csv' INTO TABLE departamento FIELDS TERMINATED BY ';' IGNORE 1 LINES (empleado_ID,departamento_ID,departamento,cargo);

 * mysql+pymysql://root:***@localhost
20 rows affected.


[]

In [19]:
%%sql
LOAD DATA INFILE 'empleados.csv' INTO TABLE empleados FIELDS TERMINATED BY ';' IGNORE 1 LINES (empleado_ID,nombre,f_nacimiento,departamento_ID, SesionLog);

 * mysql+pymysql://root:***@localhost
20 rows affected.


[]

In [20]:
%%sql
LOAD DATA INFILE 'salarios.csv' INTO TABLE salarios FIELDS TERMINATED BY ';' IGNORE 1 LINES (empleado_ID,salario,desde,hasta);

 * mysql+pymysql://root:***@localhost
20 rows affected.


[]

### Requerimiento 5. 
Obtenga salarios de todos los empleados de la compañía.

In [106]:
%%sql
select * from contacto limit 3;

 * mysql+pymysql://root:***@localhost
3 rows affected.


[(43996734, '16061004-1139', '1872 Metus. St.', 'Aliquam.fringilla.cursus@risusquisdiam.edu', '(984) 331-0597\r'),
 (70632172, '16100808-1778', 'P.O. Box 994, 9433 Auctor. Rd.', 'erat@vestibulumMauris.com', '(984) 331-3366'),
 (71292369, '16391109-8964', 'Ap #782-4900 Aliquet Street', 'nec.enim.Nunc@tinciduntDonec.com', '(462) 877-2851\r')]

In [27]:
%sql SELECT salario from salarios;

 * mysql+pymysql://root:***@localhost
20 rows affected.


[(3352,),
 (5452,),
 (1516,),
 (2458,),
 (3388,),
 (6083,),
 (5685,),
 (3765,),
 (3257,),
 (6725,),
 (1516,),
 (3063,),
 (5006,),
 (5659,),
 (7359,),
 (4145,),
 (6234,),
 (8303,),
 (5501,),
 (5946,)]

### Requerimiento 6. 
Actualice la tabla que contiene la información de los empleados ya que la columna `SesionLog` no es pertinente para la base de datos.

In [21]:
%%sql
ALTER TABLE empleados DROP SesionLog;

 * mysql+pymysql://root:***@localhost
0 rows affected.


[]

### Requerimiento 7. 
Actualice el número de teléfono del empleado con ID = 70632172 con el dato (984) 331-3366.

In [22]:
%%sql
UPDATE contacto SET telefono = "(984) 331-3366" WHERE empleado_ID = '70632172';

 * mysql+pymysql://root:***@localhost
1 rows affected.


[]

### Requerimiento 8. 
Obtenga los cargos únicos por departamento.

In [93]:
%%sql 
SELECT DISTINCT departamento,cargo  from departamento order by departamento; 

 * mysql+pymysql://root:***@localhost
13 rows affected.


[('Finanzas', 'Analista financiero\r'),
 ('Finanzas', 'Asistente \r'),
 ('Finanzas', 'Contador\r'),
 ('Finanzas', 'Manager\r'),
 ('Finanzas', 'Tesorero\r'),
 ('Produccion', 'Manager\r'),
 ('Produccion', 'Maquinista\r'),
 ('Produccion', 'Operario\r'),
 ('Produccion', 'Supervisor calidad\r'),
 ('Ventas', 'Asistente \r'),
 ('Ventas', 'Manager\r'),
 ('Ventas', 'Publisista\r'),
 ('Ventas', 'Vendedor\r')]

### Requerimiento 9. 
Obtenga el número total de empleados y el salario promedio.

In [43]:
%%sql
select count(*), avg(salario) from salarios;

 * mysql+pymysql://root:***@localhost
1 rows affected.


[(20, Decimal('4720.6500'))]

### Requerimiento 10. 
Obtenga una tabla que contenga el ID de los empleados con cargo `Asistente` y aquellos que tenga un salario mayor a `6000 USD`.

In [48]:
%%sql
select empleado_ID 
    from salarios where (salario >= 6000)
UNION
select empleado_ID
    from departamento where (cargo = 'Asistente');

 * mysql+pymysql://root:***@localhost
5 rows affected.


[(71756023,), (97571695,), (1035419453,), (1037099359,), (1037572521,)]

### Requerimiento 11. 
Obtenga una tabla que muestre la identificación de los empleados y su edad en años. 

In [102]:
%%sql
SELECT empleado_ID, TIMESTAMPDIFF(YEAR,f_nacimiento,CURDATE()) AS EDAD_AÑOS FROM empleados;

 * mysql+pymysql://root:***@localhost
20 rows affected.


[(1, 36),
 (2, 26),
 (3, 27),
 (4, 32),
 (5, 34),
 (6, 32),
 (7, 21),
 (8, 24),
 (9, 24),
 (10, 24),
 (11, 30),
 (12, 31),
 (13, 23),
 (14, 27),
 (15, 36),
 (16, 22),
 (17, 28),
 (18, 22),
 (19, 25),
 (20, 20)]

### Requerimiento 12. 
Obtenga una tabla que contenga el empleado_ID y nombre de los empleados que tienen menos de `30 años`.

In [30]:
%%sql
select * from (SELECT empleado_ID,nombre,TIMESTAMPDIFF(YEAR,f_nacimiento,CURDATE()) AS EDAD FROM empleados) 
AS table_1 where (EDAD <=30);

 * mysql+pymysql://root:***@localhost
14 rows affected.


[(70632172, 'Griffin A. Diaz', 26),
 (71292369, 'Kai P. Hamilton', 27),
 (71756023, 'Rashad X. Foreman', 24),
 (71790070, 'Walter T. Ortiz', 24),
 (71791205, 'Quamar F. Hammond', 24),
 (71792023, 'Troy J. Salinas', 30),
 (97663439, 'Armando Q. Barker', 23),
 (1014226376, 'Odysseus E. Berg', 27),
 (1017223992, 'Stephen G. Miranda', 22),
 (1035419453, 'Reed C. Bolton', 28),
 (1036612972, 'Rebecca R. Mcguire', 22),
 (1037572521, 'Gisela P. Leblanc', 25),
 (1094904931, 'Rina Z. Leonard', 20),
 (1152443179, 'Melissa X. Obrien', 21)]

### Requerimiento 13. 
Obtenga una tabla que muestre la identificación de los empleados, la duración de sus respectivos contratos en meses y cuanto tiempo resta del mismo.

In [92]:
%%sql
SELECT empleado_ID, TIMESTAMPDIFF(MONTH,desde,hasta) AS PERIODO_CONTRATACION_MESES,
TIMESTAMPDIFF(MONTH,desde,CURDATE()) AS TIEMPO_RESTANTE_MESES FROM salarios;

 * mysql+pymysql://root:***@localhost
20 rows affected.


[(43996734, 33, 28),
 (70632172, 37, 27),
 (71292369, 9, 6),
 (71315954, 14, 4),
 (71697256, 21, 18),
 (71756023, 15, 11),
 (71790070, 40, 29),
 (71791205, 12, 8),
 (71792023, 29, 18),
 (97571695, 17, 16),
 (97663439, 10, 7),
 (1014226376, 18, 12),
 (1017132659, 31, 27),
 (1017223992, 25, 22),
 (1035419453, 15, 10),
 (1036612972, 8, 4),
 (1037099359, 24, 17),
 (1037572521, 32, 28),
 (1094904931, 31, 23),
 (1152443179, 25, 24)]

### Requerimiento 14. 
Obtenga el salario promedio por departamento

In [55]:
%%sql
SELECT departamento.departamento, avg(salario) FROM salarios JOIN departamento
ON departamento.empleado_ID = salarios.empleado_ID group by departamento.departamento order by avg(salario);

 * mysql+pymysql://root:***@localhost
3 rows affected.


[('Finanzas', Decimal('2362.0000')),
 ('Produccion', Decimal('4184.6667')),
 ('Ventas', Decimal('6388.3333'))]

### Requerimiento 15. 
Obtenga el salario promedio por cargo

In [54]:
%%sql
SELECT departamento.cargo, avg(salario) FROM salarios JOIN departamento
ON departamento.empleado_ID = salarios.empleado_ID group by departamento.cargo order by avg(salario);

 * mysql+pymysql://root:***@localhost
10 rows affected.


[('Contador\r', Decimal('1516.0000')),
 ('Tesorero\r', Decimal('2458.0000')),
 ('Analista financiero\r', Decimal('3063.0000')),
 ('Operario\r', Decimal('3370.0000')),
 ('Maquinista\r', Decimal('3955.0000')),
 ('Asistente \r', Decimal('4234.0000')),
 ('Supervisor calidad\r', Decimal('5006.0000')),
 ('Manager\r', Decimal('5670.6667')),
 ('Publisista\r', Decimal('6083.0000')),
 ('Vendedor\r', Decimal('6384.6000'))]

### Requerimiento 16. 
Obtenga una tabla que contenga los datos personales del empleado, departamento, cargo y salario.

In [74]:
%%sql
SELECT nombre, f_nacimiento, departamento.departamento, departamento.cargo, salarios.salario FROM empleados 
INNER JOIN departamento ON departamento.empleado_ID = empleados.empleado_ID 
INNER JOIN salarios ON empleados.empleado_ID = salarios.empleado_ID;

 * mysql+pymysql://root:***@localhost
20 rows affected.


[('Howard A. Clarke', datetime.date(1981, 7, 17), 'Produccion', 'Operario\r', 3352),
 ('Griffin A. Diaz', datetime.date(1991, 9, 1), 'Produccion', 'Manager\r', 5452),
 ('Kai P. Hamilton', datetime.date(1991, 4, 12), 'Finanzas', 'Asistente \r', 1516),
 ('Beau U. Singleton', datetime.date(1985, 9, 1), 'Finanzas', 'Tesorero\r', 2458),
 ('Emi O. Christian', datetime.date(1985, 10, 15), 'Produccion', 'Operario\r', 3388),
 ('Rashad X. Foreman', datetime.date(1993, 10, 23), 'Ventas', 'Publisista\r', 6083),
 ('Walter T. Ortiz', datetime.date(1994, 5, 29), 'Ventas', 'Asistente \r', 5685),
 ('Quamar F. Hammond', datetime.date(1994, 6, 27), 'Produccion', 'Maquinista\r', 3765),
 ('Troy J. Salinas', datetime.date(1987, 7, 23), 'Finanzas', 'Manager\r', 3257),
 ('Neve R. Huber', datetime.date(1986, 11, 9), 'Ventas', 'Vendedor\r', 6725),
 ('Armando Q. Barker', datetime.date(1994, 12, 25), 'Finanzas', 'Contador\r', 1516),
 ('Odysseus E. Berg', datetime.date(1991, 5, 14), 'Finanzas', 'Analista financiero\r', 3063),
 ('Shafira D. Alford', datetime.date(1981, 11, 10), 'Produccion', 'Supervisor calidad\r', 5006),
 ('Stephen G. Miranda', datetime.date(1996, 3, 2), 'Ventas', 'Vendedor\r', 5659),
 ('Reed C. Bolton', datetime.date(1989, 8, 28), 'Ventas', 'Vendedor\r', 7359),
 ('Rebecca R. Mcguire', datetime.date(1996, 3, 25), 'Produccion', 'Maquinista\r', 4145),
 ('Yvonne M. Osborn', datetime.date(1984, 1, 25), 'Ventas', 'Vendedor\r', 6234),
 ('Gisela P. Leblanc', datetime.date(1993, 2, 4), 'Ventas', 'Manager\r', 8303),
 ('Rina Z. Leonard', datetime.date(1997, 11, 29), 'Ventas', 'Asistente \r', 5501),
 ('Melissa X. Obrien', datetime.date(1996, 10, 9), 'Ventas', 'Vendedor\r', 5946)]

### Requerimiento 17. 
Exporte la tabla anterior a un archivo `.csv`.

In [94]:
%%sql
SELECT nombre, f_nacimiento, departamento.departamento, departamento.cargo, salarios.salario FROM empleados 
INNER JOIN departamento ON departamento.empleado_ID = empleados.empleado_ID 
INNER JOIN salarios ON empleados.empleado_ID = salarios.empleado_ID INTO OUTFILE 'tabla_resumen.csv';

 * mysql+pymysql://root:***@localhost
20 rows affected.


[]

### Requerimiento 18. 
Obtenga una tabla que muestre el nombre, email y teléfono de los empleados que tienen entre `25 - 28 años`.

In [92]:
%%sql
select table_3.nombre, contacto.email, contacto.telefono, table_3.EDAD 
from (SELECT empleado_ID,nombre,TIMESTAMPDIFF(YEAR,f_nacimiento,CURDATE()) AS EDAD FROM empleados) 
AS table_3 JOIN contacto ON table_3.empleado_ID = contacto.empleado_ID where (EDAD BETWEEN 25 AND 28);

 * mysql+pymysql://root:***@localhost
5 rows affected.


[('Griffin A. Diaz', 'erat@vestibulumMauris.com', '(984) 331-3366', 26),
 ('Kai P. Hamilton', 'nec.enim.Nunc@tinciduntDonec.com', '(462) 877-2851\r', 27),
 ('Odysseus E. Berg', 'in@vitae.ca', '(100) 700-8357\r', 27),
 ('Reed C. Bolton', 'vitae.posuere@purus.net', '(394) 202-1731\r', 28),
 ('Gisela P. Leblanc', 'arcu.Vestibulum.ante@ullamcorperDuis.edu', '(965) 486-3764\r', 25)]

Taller práctico - SQL
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/R-for-data-science/blob/master/01-uso-interactivo.ipynb) para acceder a la última versión online

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/R-for-data-science/blob/master/01-uso-interactivo.ipynb) para ver la última versión online en `nbviewer`. 

---